services:
  api:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - "${DATA_ROOT}:/data/db"
    command: >
      sh -c "
        /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 80
      "
    restart: unless-stopped
